import { readFileSync, readdirSync } from 'node:fs'
import { join } from 'node:path'

const ICONS_DIR = join(process.cwd(), 'src/components/icons')

function loadIcons(): Array<{ name: string; svg: string }> {
  try {
    return readdirSync(ICONS_DIR)
      .filter((f) => f.endsWith('.svg'))
      .map((file) => ({
        name: file.replace(/\.svg$/, ''),
        svg: readFileSync(join(ICONS_DIR, file), 'utf8'),
      }))
  } catch {
    return []
  }
}

function sized(svg: string, size: number): string {
  // Strip any existing width/height, then inject the desired size after <svg
  return svg
    .replace(/\s(width|height)="[^"]*"/g, '')
    .replace(/<svg/, `<svg width="${size}" height="${size}"`)
}

export default function IconPreviewPage() {
  const icons = loadIcons()
  return (
    <div className="mx-auto max-w-[1200px] p-10">
      <div className="mb-8">
        <div className="mb-1 font-mono text-[10px] uppercase tracking-[1.5px] text-steel">
          Dev preview
        </div>
        <h1 className="text-[24px] font-medium tracking-[-0.5px] text-ink">
          Icon set generated by Gemini
        </h1>
        <p className="mt-2 text-[13px] text-steel">
          {icons.length} icon{icons.length === 1 ? '' : 's'} · same geometric language
          as the brand mark · single signal-orange accent · themeable via
          currentColor
        </p>
      </div>

      <div className="grid grid-cols-2 gap-3 md:grid-cols-3 lg:grid-cols-4">
        {icons.map((icon) => (
          <div
            key={icon.name}
            className="rounded-[10px] border border-bone bg-paper p-5"
          >
            <div className="mb-4 flex items-center justify-around gap-4">
              <div className="text-ink" dangerouslySetInnerHTML={{ __html: sized(icon.svg, 48) }} />
              <div className="text-ink" dangerouslySetInnerHTML={{ __html: sized(icon.svg, 24) }} />
              <div className="text-ink" dangerouslySetInnerHTML={{ __html: sized(icon.svg, 16) }} />
            </div>
            <div className="font-mono text-[11px] text-steel">{icon.name}</div>
            <div className="mt-1 flex gap-2">
              <span className="rounded-[3px] bg-paper-warm px-1.5 py-0.5 font-mono text-[9px] text-steel">
                48px
              </span>
              <span className="rounded-[3px] bg-paper-warm px-1.5 py-0.5 font-mono text-[9px] text-steel">
                24px
              </span>
              <span className="rounded-[3px] bg-paper-warm px-1.5 py-0.5 font-mono text-[9px] text-steel">
                16px
              </span>
            </div>
          </div>
        ))}
      </div>

      <div className="mt-10 rounded-[10px] border border-bone bg-paper-warm p-5">
        <div className="mb-2 font-mono text-[10px] uppercase tracking-[1.5px] text-steel">
          Color theming demo · same SVG, different parent color
        </div>
        <div className="flex items-center gap-6">
          {['text-ink', 'text-signal', 'text-green-text', 'text-amber-text', 'text-steel'].map((cls) => (
            <div
              key={cls}
              className={cls}
              dangerouslySetInnerHTML={{
                __html: icons[0] ? sized(icons[0].svg, 32) : '',
              }}
            />
          ))}
        </div>
        <div className="mt-2 font-mono text-[10px] text-steel">
          The orange accent stays orange (intentional, brand-locked); the rest of
          the icon inherits the parent text color.
        </div>
      </div>
    </div>
  )
}
