/**
 * Converts every SVG in src/components/icons/*.svg into a single React TSX module.
 *
 * Output: src/components/icons/icons.tsx
 *   - Exports one named component per icon (PascalCase + "Icon" suffix)
 *   - Each accepts a `size` prop (default 16) and standard SVG props (className, etc.)
 *   - currentColor stroke + locked orange accent (#FF4F1F) preserved
 *
 * Run after the generator:
 *   npx tsx scripts/build-icons-tsx.ts
 */

import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ICONS_DIR = join(__dirname, '..', 'src/components/icons')

function toPascal(name: string): string {
  return name
    .split('-')
    .map((p) => p[0].toUpperCase() + p.slice(1))
    .join('')
}

/**
 * Turn an SVG file's text into a JSX-safe inner-content string ready to embed
 * inside a `<svg>` JSX tag. We:
 *  - Strip the outer <svg ...> and </svg>
 *  - Replace `stroke-width`/`stroke-linecap`/`stroke-linejoin`/`fill-rule`/etc.
 *    with their camelCase JSX equivalents.
 *  - Replace `class=` with `className=` (rare but possible).
 */
function svgInnerToJsx(svg: string): { viewBox: string; inner: string } {
  const viewBoxMatch = svg.match(/viewBox="([^"]+)"/)
  const viewBox = viewBoxMatch ? viewBoxMatch[1] : '0 0 24 24'

  let inner = svg
    .replace(/^[\s\S]*?<svg[^>]*>/, '')
    .replace(/<\/svg>\s*$/, '')
    // Strip HTML comments — invalid in JSX, useless at runtime
    .replace(/<!--[\s\S]*?-->/g, '')
    .trim()

  const renames: Array<[RegExp, string]> = [
    [/\bstroke-width=/g, 'strokeWidth='],
    [/\bstroke-linecap=/g, 'strokeLinecap='],
    [/\bstroke-linejoin=/g, 'strokeLinejoin='],
    [/\bstroke-dasharray=/g, 'strokeDasharray='],
    [/\bstroke-dashoffset=/g, 'strokeDashoffset='],
    [/\bfill-rule=/g, 'fillRule='],
    [/\bclip-rule=/g, 'clipRule='],
    [/\bclip-path=/g, 'clipPath='],
    [/\btext-anchor=/g, 'textAnchor='],
    [/\bxmlns:xlink=/g, 'xmlnsXlink='],
    [/\bxlink:href=/g, 'xlinkHref='],
    [/\bclass=/g, 'className='],
  ]
  for (const [re, replacement] of renames) {
    inner = inner.replace(re, replacement)
  }

  return { viewBox, inner }
}

const files = readdirSync(ICONS_DIR)
  .filter((f) => f.endsWith('.svg'))
  .sort()

const components: string[] = []

for (const file of files) {
  const name = file.replace(/\.svg$/, '')
  const Comp = `${toPascal(name)}Icon`
  const svg = readFileSync(join(ICONS_DIR, file), 'utf8')
  const { viewBox, inner } = svgInnerToJsx(svg)

  components.push(`export function ${Comp}({ size = 16, className, ...rest }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="${viewBox}"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      aria-hidden="true"
      {...rest}
    >
      ${inner}
    </svg>
  )
}`)
}

const out = `// Auto-generated by scripts/build-icons-tsx.ts
// Source: each src/components/icons/<name>.svg generated by Gemini.
// Do not edit by hand — re-run the generator + this script to refresh.

import type { SVGProps } from 'react'

type IconProps = Omit<SVGProps<SVGSVGElement>, 'children'> & {
  size?: number | string
}

${components.join('\n\n')}
`

writeFileSync(join(ICONS_DIR, 'icons.tsx'), out, 'utf8')
console.log(`✓ Wrote ${files.length} icon components to ${ICONS_DIR}/icons.tsx`)
