// Auto-generated by scripts/build-icons-tsx.ts
// Source: each src/components/icons/<name>.svg generated by Gemini.
// Do not edit by hand — re-run the generator + this script to refresh.

import type { SVGProps } from 'react'

type IconProps = Omit<SVGProps<SVGSVGElement>, 'children'> & {
  size?: number | string
}

export function AgentIcon({ size = 16, className, ...rest }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      aria-hidden="true"
      {...rest}
    >
      <circle cx="12" cy="7" r="3" stroke="currentColor" strokeWidth="1.5" fill="none"/>
  <path d="M 9 10 L 15 10 L 15.5 18.5 L 8.5 19 Z" stroke="currentColor" strokeWidth="1.5" fill="none"/>
  <rect x="10.5" y="12" width="5" height="5" fill="#FF4F1F"/>
    </svg>
  )
}

export function AnalyticsIcon({ size = 16, className, ...rest }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      aria-hidden="true"
      {...rest}
    >
      <path d="M4 21L21 20M4 21L5 4M7 20.7L7.2 13L9.7 12.9L9.5 20.5ZM11.5 20.5L11.7 16L14.2 15.9L14 20.3ZM16 20.2L16.2 9L18.7 8.9L18.5 20Z" stroke="currentColor" strokeWidth="1.5"/><rect x="15.45" y="4" width="4" height="4" fill="#FF4F1F"/>
    </svg>
  )
}

export function ArchiveIcon({ size = 16, className, ...rest }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      aria-hidden="true"
      {...rest}
    >
      <path d="M 4 7 L 19 4 L 20 19 L 5 22 Z" stroke="currentColor" strokeWidth="1.5" fill="none"/>
  <line x1="5" y1="10" x2="18" y2="7" stroke="currentColor" strokeWidth="1.5" fill="none"/>
  <rect x="10" y="11" width="4" height="4" fill="#FF4F1F"/>
    </svg>
  )
}

export function ArrowDownIcon({ size = 16, className, ...rest }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      aria-hidden="true"
      {...rest}
    >
      <rect x="10" y="16" width="4" height="4" fill="#FF4F1F"/><path d="M3.5 4.5L20.5 3.5L21.5 20.5L4.5 21.5Z" stroke="currentColor" strokeWidth="1.5" strokeLinejoin="round"/><path d="M12 7V16" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/>
    </svg>
  )
}

export function BellIcon({ size = 16, className, ...rest }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      aria-hidden="true"
      {...rest}
    >
      <path d="M5 8C5 4 19 4 19 8L21 19L3 18L5 8Z" stroke="currentColor" strokeWidth="1.5" strokeLinejoin="round" fill="none"/><line x1="12" y1="18" x2="12" y2="20" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/><rect x="18" y="15" width="4" height="4" fill="#FF4F1F"/>
    </svg>
  )
}

export function BuildingIcon({ size = 16, className, ...rest }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      aria-hidden="true"
      {...rest}
    >
      <path d="M 5.5 21 L 18.5 21 L 17.5 4 L 6.5 5 Z M 13.25 8 L 16.25 7.75 L 16 10.75 L 13 11 Z M 13 14 L 15.75 13.75 L 15.5 16.75 L 12.75 17 Z" stroke="currentColor" strokeWidth="1.5" fill="none"/>
<rect x="8" y="8.5" width="3.5" height="3.5" fill="#FF4F1F"/>
    </svg>
  )
}

export function CalendarIcon({ size = 16, className, ...rest }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      aria-hidden="true"
      {...rest}
    >
      <path d="M4 4 L20 5 L19 20 L3 19 Z" stroke="currentColor" strokeWidth="1.5" fill="none"/>

  
  <line x1="3.5" y1="8.5" x2="19.5" y2="9.5" stroke="currentColor" strokeWidth="1.5" fill="none"/>

  
  <line x1="3.5" y1="12.5" x2="19.5" y2="13.5" stroke="currentColor" strokeWidth="1.5" fill="none"/>
  <line x1="3.5" y1="16.5" x2="19.5" y2="17.5" stroke="currentColor" strokeWidth="1.5" fill="none"/>

  
  <line x1="8" y1="4.5" x2="7" y2="19.5" stroke="currentColor" strokeWidth="1.5" fill="none"/>
  <line x1="14" y1="5" x2="13" y2="20" stroke="currentColor" strokeWidth="1.5" fill="none"/>

  
  <rect x="9.5" y="14.5" width="4" height="4" fill="#FF4F1F"/>
    </svg>
  )
}

export function ChevronDownIcon({ size = 16, className, ...rest }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      aria-hidden="true"
      {...rest}
    >
      <path d="M6 9L12 16L19 8" stroke="currentColor" strokeWidth="1.5" fill="none"/><rect x="10" y="14" width="4" height="4" fill="#FF4F1F"/>
    </svg>
  )
}

export function DocumentIcon({ size = 16, className, ...rest }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      aria-hidden="true"
      {...rest}
    >
      <path d="M5 3 L13 4 L19 10 L20 21 L4 20 Z" stroke="currentColor" strokeWidth="1.5" fill="none"/>
  
  <path d="M13 4 L19 4 L19 10 Z" stroke="currentColor" strokeWidth="1.5" fill="none"/>
  
  <rect x="15" y="6" width="5" height="5" fill="#FF4F1F"/>
    </svg>
  )
}

export function EyeIcon({ size = 16, className, ...rest }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      aria-hidden="true"
      {...rest}
    >
      <path d="M2 12.5L12 5L22 11.5L12 19Z" stroke="currentColor" strokeWidth="1.5" fill="none"/><rect x="10" y="10" width="4" height="4" fill="#FF4F1F"/>
    </svg>
  )
}

export function GridViewIcon({ size = 16, className, ...rest }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      aria-hidden="true"
      {...rest}
    >
      <path d="M4 4L11 4.5L10.5 11L4.5 10.5Z" stroke="currentColor" strokeWidth="1.5" fill="none"/><path d="M13 4.5L20 4L19.5 10.5L12.5 11Z" stroke="currentColor" strokeWidth="1.5" fill="none"/><path d="M4.5 12.5L11.5 13L11 19.5L4 19Z" stroke="currentColor" strokeWidth="1.5" fill="none"/><rect x="13.5" y="13.5" width="6" height="6" fill="#FF4F1F"/>
    </svg>
  )
}

export function HomeIcon({ size = 16, className, ...rest }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      aria-hidden="true"
      {...rest}
    >
      <path d="M4 21L5 12L21 11L20 20Z M5 12L13 4L21 11" stroke="currentColor" strokeWidth="1.5" fill="none"/><rect x="10" y="14" width="4" height="4" fill="#FF4F1F"/>
    </svg>
  )
}

export function ListViewIcon({ size = 16, className, ...rest }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      aria-hidden="true"
      {...rest}
    >
      <rect x="4" y="5" width="4" height="4" fill="#FF4F1F"/><path d="M10 7L20 6" stroke="currentColor" strokeWidth="1.5" fill="none"/><path d="M4 12L20 11" stroke="currentColor" strokeWidth="1.5" fill="none"/><path d="M4 17L20 16" stroke="currentColor" strokeWidth="1.5" fill="none"/>
    </svg>
  )
}

export function LogoutIcon({ size = 16, className, ...rest }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      aria-hidden="true"
      {...rest}
    >
      <path d="M14 21V4L5 3V20" stroke="currentColor" strokeWidth="1.5"/><path d="M10 12H21M18 9L21 12L18 15" stroke="currentColor" strokeWidth="1.5"/><rect x="7" y="10.5" width="3" height="3" fill="#FF4F1F"/>
    </svg>
  )
}

export function MessageIcon({ size = 16, className, ...rest }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      aria-hidden="true"
      {...rest}
    >
      <path d="M 4 4 L 19 3 L 18 16 L 8 17.5 L 6 20 L 4 17.5 L 3 5 Z" stroke="currentColor" strokeWidth="1.5" fill="none"/>
  <rect x="9" y="8.5" width="5" height="5" fill="#FF4F1F"/>
    </svg>
  )
}

export function PenIcon({ size = 16, className, ...rest }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      aria-hidden="true"
      {...rest}
    >
      <path d="M 4 19 L 6 16 L 17 7 L 15 9 Z" stroke="currentColor" strokeWidth="1.5" fill="none"/>
  
  <line x1="17" y1="7" x2="19" y2="5" stroke="currentColor" strokeWidth="1.5" fill="none"/>
  
  <rect x="17" y="3" width="4" height="4" fill="#FF4F1F"/>
    </svg>
  )
}

export function PeopleIcon({ size = 16, className, ...rest }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      aria-hidden="true"
      {...rest}
    >
      <path d="M5 21V15.5C5 13.0147 6.79086 11 9 11" stroke="currentColor" strokeWidth="1.5" fill="none" strokeLinecap="round"/>
<circle cx="8.5" cy="8.5" r="3" stroke="currentColor" strokeWidth="1.5" fill="none"/>
<path d="M9 13.5L19 12.5L20.5 21H7.5Z" stroke="currentColor" strokeWidth="1.5" fill="none" strokeLinejoin="round"/>
<rect x="11" y="6" width="4" height="4" fill="#FF4F1F"/>
    </svg>
  )
}

export function PlugIcon({ size = 16, className, ...rest }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      aria-hidden="true"
      {...rest}
    >
      <path d="M7 10L17 9L18 20L6 21ZM9 10L8.5 3M15 9L15.5 3" stroke="currentColor" strokeWidth="1.5"/><rect x="10" y="13.5" width="4" height="4" fill="#FF4F1F"/>
    </svg>
  )
}

export function PlusIcon({ size = 16, className, ...rest }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      aria-hidden="true"
      {...rest}
    >
      <path d="M4 11.5L20 12.5" stroke="currentColor" strokeWidth="1.5" fill="none"/>
  <path d="M11.5 4L12.5 20" stroke="currentColor" strokeWidth="1.5" fill="none"/>
  <rect x="9.5" y="9.5" width="5" height="5" fill="#FF4F1F"/>
    </svg>
  )
}

export function RefreshIcon({ size = 16, className, ...rest }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      aria-hidden="true"
      {...rest}
    >
      <path d="M5 13A8 8 0 0 1 14 20L11 19M14 20L15 17" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/><path d="M19 11A8 8 0 0 1 10 4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/><rect x="8" y="2" width="4" height="4" fill="#FF4F1F"/>
    </svg>
  )
}

export function SearchIcon({ size = 16, className, ...rest }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      aria-hidden="true"
      {...rest}
    >
      <path d="M4 8 L15 4 L19 14 L8 18 Z" stroke="currentColor" strokeWidth="1.5" fill="none"/><line x1="18" y1="15" x2="21" y2="18" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/><rect x="9.5" y="9" width="4" height="4" fill="#FF4F1F"/>
    </svg>
  )
}

export function SettingsIcon({ size = 16, className, ...rest }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      aria-hidden="true"
      {...rest}
    >
      <path d="M 19.49 15.16 L 19.17 19.17 L 15.16 19.49 L 12.00 21.90 L 8.84 19.49 L 4.83 19.17 L 4.51 15.16 L 2.10 12.00 L 4.51 8.84 L 4.83 4.83 L 8.84 4.51 L 12.00 2.10 L 15.16 4.51 L 19.17 4.83 L 19.49 8.84 L 21.90 12.00 Z" stroke="currentColor" strokeWidth="1.5" fill="none" strokeLinejoin="round"/>
  <path d="M 9 10 L 14 9 L 15 14 L 10 15 Z" stroke="currentColor" strokeWidth="1.5" fill="none"/>
  <rect x="10" y="10" width="4" height="4" fill="#FF4F1F"/>
    </svg>
  )
}

export function ShareIcon({ size = 16, className, ...rest }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      aria-hidden="true"
      {...rest}
    >
      <circle cx="11.5" cy="5.5" r="1.5" stroke="currentColor" strokeWidth="1.5" fill="none"/>
  <circle cx="5.5" cy="18.5" r="1.5" stroke="currentColor" strokeWidth="1.5" fill="none"/>
  <circle cx="18.5" cy="17.5" r="1.5" stroke="currentColor" strokeWidth="1.5" fill="none"/>
  <line x1="11.5" y1="5.5" x2="5.5" y2="18.5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" fill="none"/>
  <line x1="11.5" y1="5.5" x2="18.5" y2="17.5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" fill="none"/>
  <line x1="5.5" y1="18.5" x2="18.5" y2="17.5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" fill="none"/>
  <rect x="9.5" y="3.5" width="4" height="4" fill="#FF4F1F"/>
    </svg>
  )
}

export function ShieldIcon({ size = 16, className, ...rest }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      aria-hidden="true"
      {...rest}
    >
      <path d="M4 3L20 4L19 18.5L12.5 21.5L5 18.5Z" stroke="currentColor" strokeWidth="1.5" strokeLinejoin="round"/><rect x="10" y="10" width="4" height="4" fill="#FF4F1F"/>
    </svg>
  )
}

export function SlidersIcon({ size = 16, className, ...rest }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      aria-hidden="true"
      {...rest}
    >
      <g stroke="currentColor" strokeWidth="1.5" fill="none"><path d="M3 8 L21 9"/><circle cx="9" cy="8.3" r="2.25"/><path d="M3 16 L21 15"/></g><rect x="15" y="13.2" width="4" height="4" fill="#FF4F1F"/>
    </svg>
  )
}

export function SnowflakeIcon({ size = 16, className, ...rest }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      aria-hidden="true"
      {...rest}
    >
      <path d="M9.5 10L14.5 9.5L15 14.5L10 15Z M12.125 9.625L12 4M12.5 14.75L12.625 20M14.625 11.9375L19 7M12.5625 14.6875L19 18M9.8125 12.5L5 17.5M9.625 10.0625L5 6.5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/><rect x="10.5" y="10.5" width="3" height="3" fill="#FF4F1F"/>
    </svg>
  )
}

export function StarIcon({ size = 16, className, ...rest }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      aria-hidden="true"
      {...rest}
    >
      <path d="M12.5 2.8 L15.2 10.8 L20.5 9.5 L16.2 12.0 L21.5 14.5 L11.5 16.2 L11.8 21.0 L7.8 12.5 L2.5 15.5 L9.0 9.8 Z" stroke="currentColor" strokeWidth="1.5" fill="none"/>
  <rect x="10" y="10" width="4" height="4" fill="#FF4F1F"/>
    </svg>
  )
}

export function TrendingDownIcon({ size = 16, className, ...rest }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      aria-hidden="true"
      {...rest}
    >
      <path d="M3.5 4.5 L20.5 5 L19.5 20 L2.5 19.5 Z" stroke="currentColor" strokeWidth="1.5" fill="none"/><path d="M7 8.5 L10 11.5 L12 10.5 L15 14.5" stroke="currentColor" strokeWidth="1.5" fill="none" strokeLinecap="round" strokeLinejoin="round"/><path d="M15 14.5 L19 18.5 M16.5 18.5 L19 18.5 L19 16" stroke="currentColor" strokeWidth="1.5" fill="none"/><rect x="13" y="12.5" width="4" height="4" fill="#FF4F1F"/>
    </svg>
  )
}

export function TrendingUpIcon({ size = 16, className, ...rest }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      aria-hidden="true"
      {...rest}
    >
      <path d="M 3 20 L 7.5 13.5 L 14.5 16.5 L 18.5 9 L 21 6.5" stroke="currentColor" strokeWidth="1.5" fill="none"/>
  <rect x="17.75" y="5.75" width="4" height="4" fill="#FF4F1F"/>
  <path d="M 21 6.5 L 22 5.5 M 22 5.5 L 20 7 M 22 5.5 L 21 4" stroke="currentColor" strokeWidth="1.5" fill="none"/>
    </svg>
  )
}

export function UploadIcon({ size = 16, className, ...rest }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      aria-hidden="true"
      {...rest}
    >
      <path d="M3 18L21 17L20 20L4 21Z" stroke="currentColor" strokeWidth="1.5"/><path d="M12 16V4M8 8L12 4L16 8" stroke="currentColor" strokeWidth="1.5"/><rect x="10.5" y="9.5" width="3" height="3" fill="#FF4F1F"/>
    </svg>
  )
}
